name: Build

#on:
#  push:
#    tags:
#      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

on: workflow_dispatch

jobs:
  pyinstaller-build:
    runs-on: macos-13
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: enter src folder
        run: | 
          cd src
      - name: Create Executable
        run: |
          pyinstaller ../misc/gh.spec